"""init

Revision ID: 5752cdacc969
Revises: 
Create Date: 2026-09-05 17:56:07.713675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5752cdacc969'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('caller_id', sa.String(), nullable=True),
    sa.Column('audio_file_path', sa.String(), nullable=False),
    sa.Column('clone_probability', sa.Float(), nullable=False),
    sa.Column('social_engineering_score', sa.Float(), nullable=False),
    sa.Column('speaker_mismatch_score', sa.Float(), nullable=True),
    sa.Column('trust_novelty_score', sa.Float(), nullable=True),
    sa.Column('transaction_risk_score', sa.Float(), nullable=True),
    sa.Column('composite_risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('signal_breakdown', sa.JSON(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('matched_patterns', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speaker_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('speaker_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('embedding_vector', sa.LargeBinary(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liveness_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('call_record_id', sa.UUID(), nullable=False),
    sa.Column('challenge_text', sa.String(), nullable=False),
    sa.Column('response_transcript', sa.String(), nullable=True),
    sa.Column('digits_matched', sa.Boolean(), nullable=True),
    sa.Column('response_clone_probability', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['call_record_id'], ['call_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trust_contacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('speaker_profile_id', sa.UUID(), nullable=False),
    sa.Column('contact_name', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('call_count', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['speaker_profile_id'], ['speaker_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trust_contacts')
    op.drop_table('liveness_challenges')
    op.drop_table('speaker_profiles')
    op.drop_table('call_records')
    # ### end Alembic commands ###
